const messages = {
  after: (field, [target]) => ` ${field}必须在${target}之后`,
  alpha_dash: (field) => ` ${field}能够包含字母数字字符，包括破折号、下划线`,
  alpha_num: (field) => `${field} 只能包含字母数字字符.`,
  alpha_spaces: (field) => ` ${field} 只能包含字母字符，包括空格.`,
  alpha: (field) => ` ${field} 只能包含字母字符.`,
  before: (field, [target]) => ` ${field} 必须在${target} 之前.`,
  between: (field, [min, max]) => ` ${field} 不在合法范围之间.`,
  numberInRange: (field, [min, max]) => ` ${field} 不在合法范围之间.`,
  confirmed: (field, [confirmedField]) => ` ${field} 不能和${confirmedField}匹配.`,
  date_between: (field, [min, max]) => ` ${field}必须在${min}和${max}之间.`,
  date_format: (field, [format]) => ` ${field}必须在在${format}格式中.`,
  decimal: (field, [decimals] = ['*']) => ` ${field}必须是数字的而且能够包含${decimals === '*' ? '' : decimals}位小数.`,
  digits: (field, [length]) => ` ${field} 必须是数字，且精确到 ${length}数`,
  dimensions: (field, [width, height]) => ` ${field}必须是 ${width} 像素到 ${height} 像素.`,
  email: (field) => ` ${field} 必须是有效的邮箱.`,
  ext: (field) => ` ${field} 必须是有效的文件.`,
  image: (field) => ` ${field} 必须是图片.`,
  in: (field) => ` ${field} 必须是一个有效值.`,
  ip: (field) => ` ${field} 必须是一个有效的地址.`,
  max: (field, [length]) => ` ${field}长度不能大于${length}字符.`,
  mimes: (field) => ` ${field} 必须是有效的文件类型.`,
  min: (field, [length]) => ` ${field}必须至少有 ${length} 字符.`,
  not_in: (field) => ` ${field}必须是一个有效值.`,
  numeric: (field) => ` ${field} 只能包含数字字符.`,
  regex: (field) => ` 请输入正确的${field}.`,
  required: (field) => `${field}不能为空.`,
  size: (field, [size]) => ` ${field} 必须小于 ${size} KB.`,
  url: (field) => ` ${field}不是有效的url.`,
  taskExist: (field) => ` ${field}不能重复，请修改`,
  alarmExist: (field) => ` ${field}不能重复，请修改`,
  array: (field) => ` ${field}不能为空`,
  usersDisabled: (field) => ` ${field}必须包含当前用户`,
  filterSuffix: (field) => `后缀括号不能为空`,
  existGroupName: (field) => `分组名称不能重复`,
  isNumberRange: (field) => `数值区间格式不正确`,
  isStartMoreThanEndValue: (field) => `区间起始值不能大于区间结束值`,
  isStartTimeMoreThanEndTime: () => `开始时间不能大于结束时间`,
  isNumber: () => `只能输入数字`,
  valueRules: (field) => `${field}已存在`,
  isNumberInRange: (field) => `输入值不在字段的区间范围内`,
  moreThanNumberEquals: () => `输入值不在范围之内`,
  lessThanNumberEquals: () => `输入值不在范围之内`,
  specialCharacterRule: (field) => `${field}不能包含逗号、冒号、分号或 '|' `,
  isKeyword: () => `输入值不能为关键字`,
  isDate: (field) => `${field}不能为空`,
  sumValidate: (field) => `${field}和值不等于100`,
  repeatValues: (field) => `字段取值区间完全重复`,
  nameTooLong: (field) => `${field}不能超过30个字符`,
  veryLong: (field) => `${field}不能超过100个字符`,
  nameCharacter: (field) => `${field}只能输入中文、英文、数字或'_'`,
  nameInitial: (field) => `${field}首位不能为特殊字符`,
  nameExist: (field) => `${field}已存在`,
  codeCharacter: (field) => `${field}只能输入数字、英文字母或'_'`,
  codeInitial: (field) => `${field}首字符不能为下划线`,
  keywordConflict: (field) => `特殊名称已被占用`
}

const locale = {
  name: 'zh_CN',
  messages,
  attributes: {}
}

export default locale
